#!/bin/bash

set -e

if [[ -n "${THE_BOOTSTRAP_APPROACH_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Run tests.
"
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
    if [[ "${1:-}" == "--help" ]]; then
        usage
    else
        ./.venv/bin/tox
    fi
fi
